<script type='text/javascript'>
function addclienteordenalbaran() {
    var form = dojo.byId("clienteorden");

    if (form == null ) return;
    
    dojo.connect(form, "onsubmit", function(event) {
        //Stop the submit event since we want to control form submission.
        dojo.stopEvent(event);

        //The parameters to pass to xhrPost, the form, how to handle it, and the callbacks.
        //Note that there isn't a url passed.  xhrPost will extract the url to call from the form's
        //'action' attribute.  You could also leave off the action attribute and set the url of the xhrPost object
        //either should work.
        var xhrArgs = {
            form: dojo.byId("clienteorden"),
            handleAs: "text",
            load: function(data) {
        		dojo.byId("errorajax").innerHTML = data;
            },
            error: function(error) {
                dojo.byId("errorajax").innerHTML = "Error agregando orden cliente ...";
            }
        };
        //Call the asynchronous xhrPost
        dojo.byId("errorajax").innerHTML = "Salvando Orden Cliente ...";
        var deferred = dojo.xhrPost(xhrArgs);
    });
}
dojo.addOnLoad(addclienteordenalbaran);

</script>



	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{
		
		if (isset($this->cliente))
		{
			$codigocliente = '430.' . $this->cliente['cuentaventa'];
			if ($this->albaran['entrada']=='1')
			{
				$codigocliente = '400.'. $this->cliente['cuentacompra'];	
			}
			
			$this->titleView='Albaran ['. $this->albaran['numeroalbaran'] .']';
			echo '<h3><table width="95%"><tr><td align="left">'.$codigocliente.'</td><td align="center">' .
			 	$this->cliente['nombre'] . '</td><td>' .  
			 	'</td><td id="idCliente" align="right"> ' .$this->cliente['idCliente'].'</td></tr></table></h3>';
			
			echo '<div id="subcontent">';
			// Annadir form para comentario y orden pedido
			
			if ($this->albaran['estado']=='0')
			{
				$url = 'http://'.$_SERVER['SERVER_NAME'].'/gestion/public/index.php/';
				$ordencliente = $this->albaran['ordencliente'];
				if ($ordencliente == '')
				{
					$ordencliente='Escribe Orden cliente y Pulsa en Salvar OC';
				}
				echo '<form action="'.$url.'albaran/adddatatoobject/idAlbaran/'.$this->albaran['idAlbaran'].'" id="clienteorden">';
				echo '<table border="0" style="margin: 5px 0 5px 0;"><tbody><tr>';
				echo '<td><input id="ordencliente" type="text" value="'.$ordencliente.'" name="ordencliente" onfocus="javascript:this.value=\'\'" style="width:500px;"/></td>';
				echo '<td><input type="submit" value="Salvar OC"></td></tr></tbody></table></form>';
 				
				echo '<div id="errorajax"></div>';
			}
			else
			{
	        	echo '<table border="0" style="margin: 5px 0 5px 0;"><tbody><tr>';
	        	echo '<td>Num Proveedor : </td><td>'.$this->cliente['numrefproveedor'].'</td>';
				echo '<td>Orden Cliente : </td><td>'.$this->albaran['ordencliente'].'</td>';
				echo '<td>Descuento : </td><td>'.$this->albaran['descuentoaplicartotal'].'</td>';
				echo '</tr></tbody></table>';
			}	
	        echo '</div>';
	        
	        
		}
		else
		{

		}
					
		if (isset($this->albaran))
		{
			if ($this->albaran['estado'] == '0')
			{
				echo $this->partial('base/nuevomovimiento.phtml',$this->paramspartial);
			}
			else
			{
				//echo '<div id="errorajax"></div>';
			}
		 }
		 echo '<div id="listadomovimientos">'.$this->listadodiv.'</div>';
		 
		 if ($this->albaran['estado']=='0')
		{
			 echo '<div id="subcontent">'; 	
			if ( isset($this->descuentos) && ($this->descuentos->count()>0))
			{
				echo $this->table('Descuentos Cliente <a href="'.$this->url(array('controller' => 'cliente', 
						'action' => 'adddescuento' , 'idAlbaran' => $this->albaran['idAlbaran'],'idCliente' => $this->albaran['idCliente']  )
						, 'default', true).'" title="Agregar mas Descuentos"><img src="img/icons/add.png"/></a>',
				array(
					'descuento' => 'Descuento',
					'tipoDescuento' => 'Tipo',
					'descripcion' => 'Aplicable'
				),
				$this->descuentos ,
				array(
					array('controller' => 'cliente', 'action' => 'editdescuento' , 'idAlbaran' => $this->albaran['idAlbaran'],'idCliente' => $this->albaran['idCliente'] 
					)
				),
				array('img/icons/edit.png" title="Editar descuento'),
				'idDescuento','ASC','idDescuento','albaran'); 
			}
			else
			{
				echo 'No hay descuentos definidos para este cliente. <a href="'.$this->url(array('controller' => 'cliente', 
						'action' => 'adddescuento' , 'idAlbaran' => $this->albaran['idAlbaran'],'idCliente' => $this->albaran['idCliente']  )
						, 'default', true).'"><img src="img/icons/add.png"/></a>';
			}
			echo '</div>';
		}
	}?>
	
