
<div id="listadomovimientos">

	<?php
	
	if (isset($this->movimientos))
	{
		$listactions = array();
		$listicons = array();
		$tableview = '';
		if ($this->objeto['estado'] == '0')
		{
			$listactions = array(
					array('controller' => $this->controller, 'action' => 'editmovimiento', $this->idKey => $this->idkeyvalue,'idCliente'=>$this->idCliente),
					array('controller' => $this->controller, 'action' => 'deleteajaxmovimiento',$this->idKey => $this->idkeyvalue,'idCliente'=>$this->idCliente)
					);
			//$listicons = array();
			$listicons = array('img/icons/edit.png" title="Cambiar Cantidades','img/icons/delete.png" title="Borrar Movimiento');
		}
		else
		{		
			$tableview = 'Listado Movimientos';
		}
		
		echo $this->table($tableview ,
				array(
					'calidad' => 'Calidad',
					'color' => 'Color',
					'tipoenvase' => 'Env.',
					'descripcion' => 'Descripcion',
					'tcantidad' => '#',
					'precio' => 'Euros',
					'descuento' => '%',
					'tprecio' => 'Valor',
				),
				$this->movimientos ,
				$listactions,
				$listicons,
				'idMovimiento','ASC','idMovimiento'); 
	}
	
	$url = 'http://'.$_SERVER['SERVER_NAME'].'/gestion/public/';
	if ($_SERVER['SERVER_NAME']!='localhost')
	{
		$url .= 'index.php/';
	}
	echo '<div id="subcontent">';
	echo '<form method="post" action="'.$url.$this->escape($this->controller).'/finalizardocumento/'.
										$this->escape($this->idKey).'/'.$this->escape($this->idkeyvalue).
		        '" id="finalizardocumento">';

?>
		

	<table align="center"><tbody><tr>
	<?php if (isset($this->movimientos) && ($this->movimientos->count() > 0 ) && ( $this->objeto['estado'] == '0' ) ) { ?>
		<td>Descuento Total: <?php echo $this->selectDescuento; ?></td>
		<td><input type="submit" name="finaldocumento" value="Imprimir & Guardar"/></td>
		<td><input type="submit" name="finaldocumento" value="Solo Guardar"/></td>
	<?php } 
		if ( $this->objeto['estado'] == '1' ) 
		{?>
			<td><input type="submit" name="finaldocumento" value="Volver a Imprimir"/></td>
	<?php
			if ($this->controller == 'Albaran' ) 
			{ ?>
				<td><input type="submit" name="finaldocumento" value="Facturar"/></td>
		<?php 
			} ?>
	<?php 	
		}	?>	
		<td><input type="submit" name="finaldocumento" value="Salir"/></td>
		</tr></tbody></table></form>
		</div>
</div>

