


<script type='text/javascript'>
function sendNuevoMovimiento() {
    var form = dojo.byId("nuevomovimiento");

    dojo.connect(form, "onsubmit", function(event) {
        //Stop the submit event since we want to control form submission.
        dojo.stopEvent(event);

        //The parameters to pass to xhrPost, the form, how to handle it, and the callbacks.
        //Note that there isn't a url passed.  xhrPost will extract the url to call from the form's
        //'action' attribute.  You could also leave off the action attribute and set the url of the xhrPost object
        //either should work.
        var xhrArgs = {
            form: dojo.byId("nuevomovimiento"),
            handleAs: "text",
            load: function(data) {
        		dojo.byId("listadomovimientos").innerHTML = data;
        		
        		//dijit.byId("tipoenvase").attr('autocomplete', false);
        		dijit.byId("tipoenvase").attr("value",null);
        		dojo.byId("cantidad").value = "";
        		//dijit.byId("color").attr('autocomplete', false);
        		dijit.byId("color").attr("value", null);
        		//http://www.javascript-coder.com/javascript-form/javascript-reset-form.phtml
        		//dijit.byId("calidad").attr('autocomplete', false);
        		dijit.byId("calidad").attr("value", null);


        		
            },
            error: function(error) {
                dojo.byId("listadomovimientos").innerHTML = "Error Agregando movimientos.. Es el producto correcto?";
            }
        };
        //Call the asynchronous xhrPost
        dojo.byId("listadomovimientos").innerHTML = "Agregando movimiento...";
        var deferred = dojo.xhrPost(xhrArgs);
    });
}
dojo.addOnLoad(sendNuevoMovimiento);
</script>

<div id="subcontent">
<?php 
    $url = 'http://'.$_SERVER['SERVER_NAME'].$this->baseUrl().'index.php/';

	// controller : albaran o factura
	// idKey . idAlbaran o idFactura
	// idValue . el valor de idKey.
echo '<h3> Introducir movimientos</h3>';
echo '<form action="'.$url.$this->escape($this->controller).'/addmovimientoajax/format/ajax/'.
			$this->escape($this->idKey).'/'.$this->escape($this->idValue).
	        '" id="nuevomovimiento"><table class="dbtableref">'.
	        '<tbody><tr><td id="tdref">';

$element = new Zend_Dojo_Form_Element_FilteringSelect('calidad');
            $element->setAutoComplete(false)
			->setStoreId('autocompleter')
			->setStoreType('js.custom.AutocompleteCalidad')
			->setStoreParams(array('url'=>$url.'stock/autocompletecalidad'))
			->setAttrib('searchAttr', 'calidad')
			->setLabel('Calidad')
			->setRequired(true);
echo $element.'</td><td id="tdref">';

$element2 = new Zend_Dojo_Form_Element_FilteringSelect('color');
            $element2->setAutoComplete(false)
			->setStoreId('autocompleter2')
			->setStoreType('js.custom.AutocompleteColor')
			->setStoreParams(array('url'=>$url.'stock/autocompletecolor'))
			->setAttrib('searchAttr', 'color')
			->setLabel('Color')
			->setRequired(true);
echo $element2.'</td><td id="tdref">';

$element3 = new Zend_Dojo_Form_Element_FilteringSelect('tipoenvase');
            $element3->setAutoComplete(false)
			->setStoreId('autocompleter3')
			->setStoreType('js.custom.AutocompleteTipoenvase')
			->setStoreParams(array('url'=>$url.'stock/autocompletetipoenvase'))
			->setAttrib('searchAttr', 'tipoenvase')
			->setLabel('TipoEnvase')
			->setRequired(true);
echo $element3.'</td><td id="tdref">';			

$element4 = new Zend_Form_Element_Text( 'cantidad');
$element4->setLabel('Cantidad(#)')
		 ->setRequired(true);
		 
echo $element4.'</td><td id="tdref">';	

			$list = array();
			$list['1'] = 'salida o factura';
			$list['-1'] = 'entrada o abono';
			
			require_once(APPLICATION_PATH . '/models/ModelCliente.php');
			$modelCliente = new ModelCliente();
			
			$list2 = $modelCliente->queryToDisplayValues('TblDescuento',$this->escape($this->idCliente));
			$list2['0'] = '0';
			$list2['100'] = '100';
			$defdesc = $modelCliente->getDefaultDescuento($this->escape($this->idCliente));
			
			
 $element5 = new Zend_Form_Element_Select(  'salida');
 $element5->setLabel('Salida')
 		   ->addMultiOptions($list)
		   ->setRequired(true);
		   
if ($this->escape($this->entrada) == '1')
	$element5->setValue('-1');
else
	$element5->setValue('1');
	
echo $element5.'</td><td id="tdref">';	
		
 $element6 = new Zend_Form_Element_Select( 'descuento');
 $element6->setLabel('Descuento(%)')
 			->setRequired('true')
 			->addMultiOptions($list2);
 $element6->setValue($defdesc);
 echo $element6.'</td><td id="tdref">';	
      		
 $element7 = new Zend_Form_Element_Submit( 'Agregar');
echo $element7.'</td>';	


echo '</tr></tbody></table></form>';
			
?>

</div>

