
	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{	
		if ( isset($this->goalTitle ))
		{
		   ?>
	
		   <div id="subcontent">
				<h2>Goal : <?php echo $this->goalTitle; ?> </h2>
			</div>
			<?php 
		    }
		    
		if (isset($this->idGoal))
		{
			$url = '<a href="'.$this->url(array('controller' => 'strategy', 
				'action' => 'add', 'idGoal' => $this->idGoal )
				, 'default', true).'"><img src="img/icons/add.png"/></a>';
		}
		else
		{
			$url = 'Summary';
		}
		 echo $this->table('Strategies ' .  $url ,
				array(
				  /*  'idGoal' => 'id',*/
					'titleStrategy' => 'Title',
					'descStrategy' => 'Description'
				),
				$this->strategies ,
				array(
					array('controller' => 'strategy', 'action' => 'edit', 'idGoal' => $this->idGoal ),
					array('controller' => 'strategy', 'action' => 'delete', 'idGoal' => $this->idGoal ),
					array('controller' => 'task', 'action' => 'index' )
				),
				array('img/icons/edit.png','img/icons/delete.png','img/icons/task.png'),
				'idStrategy','ASC','idStrategy'); 
	}?>
