<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>Leitmotif</title>
	<base href="<?php echo 'http://'.$_SERVER['SERVER_NAME'].':' . $_SERVER['SERVER_PORT'] . $this->baseUrl().'/';?>" />
	<?php
		echo $this->headLink()->appendStylesheet('css/main.css', 'screen, projection');

	?>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script src="custom/leitmotif.js"></script> 
</head>
<body>
	<header><h1>Leitmotif</h1></header>
	
	<div>
		<?php echo $this->layout()->content;?>
	</div>

</body>

</html>
