		
			<div id="login">
				<p>Por favor, entrar:</p>
				<p style="clear:both"></p>
				<?php

				$auth = Zend_Auth::getInstance();
				if($auth->hasIdentity()) {
					?>
					Bienvenid@ <?php echo $auth->getIdentity()->titleUser ?> -
					<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), 'default', true) ?>">Salir</a>
					<?php
					
				}
				else{		
					 		
				?>
				   
					<form method="post" id="loginform" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'login'), 'default', true) ?>">
						
						<input type="text" name="username" id="username" value="id usuario" onfocus="javascript:this.value=''" onkeypress="if (event.keyCode == 13) document.getElementById('loginform').submit();" />
						<br/>
						<input type="password" name="password" id="password" value="Clave" onfocus="javascript:this.value=''" onkeypress="if (event.keyCode == 13) document.getElementById('loginform').submit();" />
						<!--  <a href="javascript:document.getElementById('loginform').submit();">Login</a>    -->
						<br/><input type="submit" value="Login"/>
					</form>
					<br/>

				<?php }?>
				
			</div>
			