<script>
        dojo.require("dijit.form.DateTextBox");
</script>
	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{	
		if (isset($this->cliente))
		{
		
			$this->titleView='Factura ['. $this->factura['numerofactura'] .']';
			echo '<h3><table width="95%"><tr><td align="left"> 430.' .$this->cliente['cuentaventa'].'</td><td align="center">' .
			 	$this->cliente['nombre'] . '</td><td>' .  
			 	'</td><td id="idCliente" align="right"> ' .$this->cliente['idCliente'].'</td></tr></table></h3>';
			echo 'Orden Cliente ['.$this->factura['ordencliente'].']';
			
			echo '<div id="subcontent">';
			if ($this->factura['estado']=='0')
			{
				
				echo '<form method="post" id="cambiopago"  action="'.$this->url(array('controller' => 'factura', 'action' => 'cambiopagofactura','idFactura'=>$this->factura['idFactura']), 'default', true) .'">';			
				echo '<table class="dbtableref">'; 	
					
				echo '<tr><td><input id="fecha" type="text" value="'. $this->factura['fecha'].'" name="fecha" style="width:110px" name="posterior" dojoType="dijit.form.DateTextBox" /></td>';
				
			
				if (isset($this->selectTipopago)) echo '<td>'.$this->selectTipopago.'</td>';
				if (strcmp($this->factura['condicionespago'],'contado')==0)
				{
					//echo 'CONTADO    ';
				}
				else
				{
					echo '<td>' .$this->cliente['vencimiento'].' dias</td>';
					echo '<td><input id="vencimiento" type="text" value="'. $this->factura['vencimiento'].'" name="vencimiento" style="width:110px" name="posterior" dojoType="dijit.form.DateTextBox" /></td>';
				}
				echo '<td><input type="submit" value="Cambiar"/></td></tr></table></form>';	
				echo '<br/>';
				if ( isset($this->descuentos) && ($this->descuentos->count()>0))
				{
					echo $this->table('Descuentos Cliente <a href="'.$this->url(array('controller' => 'cliente', 
						'action' => 'adddescuento' , 'idFactura' => $this->factura['idFactura'],'idCliente' => $this->factura['idCliente']  )
						, 'default', true).'" title="Agregar mas Descuentos"><img src="img/icons/add.png"/></a>',
						array(	'descuento' => 'Descuento',
							'tipoDescuento' => 'Tipo',
							'descripcion' => 'Aplicable'),
							$this->descuentos ,
						array(
							array('controller' => 'cliente', 'action' => 'editdescuento' , 
									'idFactura' => $this->factura['idFactura'],
									'idCliente' => $this->factura['idCliente'] 
								)),
						array('img/icons/edit.png" title="Editar descuento'),
							'idDescuento','ASC','idDescuento','factura'); 
				}
				else
				{
					echo 'No hay descuentos definidos para este cliente. <a href="'.$this->url(array('controller' => 'cliente', 
						'action' => 'adddescuento' , 'idFactura' => $this->factura['idFactura'],'idCliente' => $this->factura['idCliente']  )
						, 'default', true).'"><img src="img/icons/add.png"/></a>';
				}
			}
			else
			{
				$date = new Zend_Date($this->factura['fecha']);
				$dateprint= $date->toString('dd-MM-YYYY');
				$vencimiento = new Zend_Date($this->factura['vencimiento']);
				$vencimientoprint= $vencimiento->toString('dd-MM-YYYY');
				echo '<table border="0" style="margin: 5px 0 5px 0;"><tbody>';
				echo '<tr><td>Fecha</td><td>' .  $dateprint . '</td><td>Vencimiento</td><td>'.$vencimientoprint.'</td></tr>';
				echo '<tr><td>Condiciones Pago</td><td>'.$this->factura['condicionespago'].'</td></tr>';
				echo '<tr><td>Bruto</td><td>'.$this->factura['bruto'].'</td><td>Base Imponible</td><td>'.$this->factura['baseimponible'].'</td></tr>';
				echo '<tr><td>Descuento %</td><td>'.$this->factura['descuentoaplicartotal'].'</td><td>Descuento</td><td>'.$this->factura['descuento'].'</td></tr>';
				echo '<tr><td>Iva</td><td>'.$this->factura['iva'].'</td><td>Total</td><td>'.$this->factura['total'].'</td></tr>';
				echo '</tbody></table>';
			}
			
			echo '</div>';
		}

		?>
		<div id="subcontent">
		
		<?php 
		if (isset($this->albarabesestafactura))
		{
			$acciones = array();
				$iconos = array();
				if ($this->factura['estado']=='0')
				{
					$acciones = array(array('controller' => 'factura', 'action' => 'desasignarfacturaalbaran' , 'idFactura' => $this->factura['idFactura']));
					$iconos = array('img/icons/delete2.png" title="No incluir este albaran');
				}
			echo $this->table('Albaranes incluidos en esta factura',
				array(
					'numeroalbaran' => 'Albaran',
					'fecha' => 'Fecha',
					'ordencliente' => 'Orden Cliente',
					'entrada' => 'E/S',
					'tienda' => 'Tienda'
				),
				$this->albarabesestafactura ,
				$acciones,
				$iconos,
				'idAlbaran','ASC','idAlbaran','factura'); 
			
		}
		else
		{
			echo 'No hay albaranes includidos</h3>';
		}

		if ($this->factura['estado']=='0')
		{
			echo '<br/>';
			if ( isset($this->albaranespendientes)&&($this->albaranespendientes->count()>0))
			{
			echo $this->table('Albaranes Pendientes del mismo Cliente',
				array(
					'numeroalbaran' => 'Albaran',
					'fecha' => 'Fecha',
					'ordencliente' => 'Orden Cliente',
					'entrada' => 'E/S',
					'tienda' => 'Tienda'
				),
				$this->albaranespendientes ,
				array(
					array('controller' => 'factura', 'action' => 'asignarfacturaalbaran' , 'idFactura' => $this->factura['idFactura'])
				),
				array('img/icons/add.png" title="Incluir este albaran'),
				'idAlbaran','ASC','idAlbaran','factura'); 
			
			}
			else
			{
				echo 'No hay mas albaranes Pendientes del mismo Cliente';
			}
			echo '<br/></div>';
			echo $this->partial('base/nuevomovimiento.phtml',$this->paramspartial);
		}
		else
		{
			echo '</div>';
		}
				 
		echo '<div id="listadomovimientos">'.$this->listadodiv.'</div>';
	}
?>


