<script>
        dojo.require("dijit.form.DateTextBox");
</script>
	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{
		
		if (isset($this->cliente))
		{
			echo '<div id="subcontent"><table width="100%" border="0" style="color:#ff0099;
	margin: 5px 0 5px 0;"><h3><tr><td>' . $this->cliente['nombre'] . '</td><td align="right">' . $this->factura['numerofactura']  .'</td></tr></table></h3>';
			echo '<br/>';
			if ($this->factura['estado']=='0')
			{
		
				echo '<form method="post" id="cambiopago"  action="'.$this->url(array('controller' => 'factura', 'action' => 'cambiopagofactura','idFactura'=>$this->factura['idFactura']), 'default', true) .'">';			
				echo '<table class="dbtableref"><tr>'; 		
				echo '<td><input id="fecha" type="text" value="'. $this->factura['fecha'].'" name="fecha" style="width:110px" name="posterior" dojoType="dijit.form.DateTextBox" /></td>';
				
			
				if (isset($this->selectTipopago)) echo '<td>'.$this->selectTipopago.'</td>';
				if (strcmp($this->factura['condicionespago'],'contado')==0)
				{
					//echo 'CONTADO    ';
				}
				else
				{
					echo '<td>' .$this->cliente['vencimiento'].' dias</td>';
					echo '<td><input id="vencimiento" type="text" value="'. $this->factura['vencimiento'].'" name="vencimiento" style="width:110px" name="posterior" dojoType="dijit.form.DateTextBox" /></td>';
				}
				echo '<td><input type="submit" value="Cambiar"/></td></tr></table></form>';	
			}
			else
			{
				echo '<table class="dbtableref"><tbody><tr><td>' .  $this->factura['fecha'] . '</td><td>'.$this->factura['condicionespago'].'</td><td>Vencimiento</td><td>'.$this->factura['vencimiento'].'</td></tr></tbody></table>';
			}
			echo '<br/>';
			if ( isset($this->descuentos) && ($this->descuentos->count()>0))
			{
				echo $this->table('Descuentos Cliente <a href="'.$this->url(array('controller' => 'cliente', 
						'action' => 'adddescuento' , 'idFactura' => $this->factura['idFactura'],'idCliente' => $this->factura['idCliente']  )
						, 'default', true).'" title="Agregar mas Descuentos"><img src="img/icons/add.png"/></a>',
				array(
					'descuento' => 'Descuento',
					'descripcion' => 'Aplicable'
				),
				$this->descuentos ,
				array(
					array('controller' => 'cliente', 'action' => 'editdescuento' , 'idFactura' => $this->factura['idFactura'],'idCliente' => $this->factura['idCliente'] 
					)
				),
				array('img/icons/edit.png" title="Editar descuento'),
				'idDescuento','ASC','idDescuento','factura'); 
			}
			else
			{
				echo 'No hay descuentos definidos para este cliente. <a href="'.$this->url(array('controller' => 'cliente', 
						'action' => 'adddescuento' , 'idFactura' => $this->factura['idFactura'],'idCliente' => $this->factura['idCliente']  )
						, 'default', true).'"><img src="img/icons/add.png"/></a>';
			}
			echo '<br/></div>';
		}
		else
		{

		}
		?>
		<div id="subcontent">
		

		<?php 
		if (isset($this->albarabesestafactura))
		{
			$acciones = array();
				$iconos = array();
				if ($this->factura['estado']=='0')
				{
					$acciones = array(array('controller' => 'factura', 'action' => 'desasignarfacturaalbaran' , 'idFactura' => $this->factura['idFactura']));
					$iconos = array('img/icons/delete2.png" title="No incluir este albaran');
				}
			echo $this->table('Albaranes incluidos en esta factura',
				array(
					'numeroalbaran' => 'Albaran',
					'fecha' => 'Fecha',
					'nombre' => 'Cliente',
					'entrada' => 'E/S',
					'tienda' => 'Tienda'
				),
				$this->albarabesestafactura ,
				$acciones,
				$iconos,
				'idAlbaran','ASC','idAlbaran','factura'); 
			
		}
		else
		{
			echo 'No hay albaranes includidos</h3>';
		}
		echo '<br/>';
		if ($this->factura['estado']=='0')
		{

			if ( isset($this->albaranespendientes)&&($this->albaranespendientes->count()>0))
			{
			echo $this->table('Albaranes Pendientes del mismo Cliente',
				array(
					'numeroalbaran' => 'Albaran',
					'fecha' => 'Fecha',
					'nombre' => 'Cliente',
					'entrada' => 'E/S',
					'tienda' => 'Tienda'
				),
				$this->albaranespendientes ,
				array(
					array('controller' => 'factura', 'action' => 'asignarfacturaalbaran' , 'idFactura' => $this->factura['idFactura'])
				),
				array('img/icons/add.png" title="Incluir este albaran'),
				'idAlbaran','ASC','idAlbaran','factura'); 
			
			}
			else
			{
				echo 'No hay mas albaranes Pendientes del mismo Cliente';
			}
			echo '<br/>';
		}	
		?>
		</div>
		
		

		<?php 
		if (isset($this->factura))
		{
			if (isset($this->movimientos))
			{
				$tableview = $this->subtitleView;
				if ($this->factura['estado'] == '0')
				{
					$tableview .= '<a title="Agregar referencia" href="'.$this->url(array('controller' => 'factura', 
						'action' => 'addmovimiento' , 'idFactura' => $this->factura['idFactura'] )
						, 'default', true).'"><img src="img/icons/add.png"/></a>';
				}
				$acciones = array();
				$iconos = array();
				if ($this->factura['estado']=='0')
				{
					$acciones = array(
						array('controller' => 'factura', 'action' => 'editmovimiento','idFactura' => $this->factura['idFactura']),
						array('controller' => 'factura', 'action' => 'deletemovimiento','idFactura' => $this->factura['idFactura']));
					$iconos = array('img/icons/edit.png" title="Editar esta referencia',
									'img/icons/delete.png" title="Eliminar esta referencia');
				}
				
			echo $this->table($tableview ,
				array(
					'calidad' => 'Calidad',
					'color' => 'Color',
					'tipoenvase' => 'Env.',
					'tcantidad' => '#',
					'precio' => 'Euros',
					'descuento' => '%',
					'tprecio' => 'Valor',
					'descripcion' => 'Descripcion'
				),
				$this->movimientos ,
				$acciones,
				$iconos,
				'idMovimiento','ASC','idMovimiento'); 
			}
			?>	
			<!-- Tabla para finalizar -->
			<form method="post" id="finalizardocumento" action="<?php echo $this->url(array('controller' => 'factura', 'action' => 'finalizardocumento', 'idFactura' => $this->factura['idFactura']), 'default', true); ?>">			
			<table align="center"><tbody><tr>
			<?php if (isset($this->movimientos) && ($this->movimientos->count() > 0 ) && ( $this->factura['estado'] == '0' ) ) { ?>
				<td><input type="submit" name="finaldocumento" value="Imprimir & Guardar"/></td>
				<td><input type="submit" name="finaldocumento" value="Solo Guardar"/></td>
			<?php } if ( $this->factura['estado'] == '1' ) {?>
				<td><input type="submit" name="finaldocumento" value="Recalcular & Imprimir"/></td>
				<td><input type="submit" name="finaldocumento" value="Volver a Imprimir"/></td>
			<?php 	}	?>	
			<td><input type="submit" name="finaldocumento" value="Salir"/></td>
			</tr></tbody></table></form>
			<?php 
			
		}
	}?>
	
