

	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{	
	?>
		
		<form method="post" id="grapequery" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('controller' => 'catalogue', 'action' => 'index'), 'default', true) ?>">			
		<p><input type="text" name="searchgrape" id="searchgrape" value="Search grape" onfocus="javascript:this.value=''" onkeypress="if (event.keyCode == 13) document.getElementById('grapequery').submit();" />
		<input type="submit" value="Search"/></p>
		</form>

		
		<?php 
	
		
		if (isset($this->grapes))
		{
			echo $this->table('Grapes <a title="New Grape" href="'.$this->url(array('controller' => 'catalogue', 
				'action' => 'addgrape' )
				, 'default', true).'"><img src="img/icons/add.png"/></a>',
				array(
					'grapename' => 'Grape Name',
					'winetype'  => 'Wine Type'
				),
				$this->grapes ,
				array(
					array('controller' => 'catalogue', 'action' => 'editgrape'),
					array('controller' => 'catalogue', 'action' => 'deletegrape'),
				),
				array('img/icons/edit.png" title="Edit Grape','img/icons/delete.png" title="Delete Grape'),
				'grapeId','ASC','grapeId'); 
			echo '<br/>';
		}
			
	}
	?>
