<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl">
<head>
	<title>Diviner</title>
	<base href="<?php echo 'http://'.$_SERVER['SERVER_NAME'].':' . $_SERVER['SERVER_PORT'] . $this->baseUrl().'/';?>" />
	<?php
		echo $this->headLink()->appendStylesheet('css/main.css', 'screen, projection');
		if ($this->dojo()->isEnabled()){

    		//$this->dojo()->setLocalPath('js/dojo.js')
            //     ->addStyleSheetModule('dijit.themes.tundra');
            //     echo $this->dojo();
            //$this->dojo()->setLocalPath('js/dojo.gestion.js');
                	
            
		}
	?>

</head>
<body >

	
	<!-- Heading with login/logout -->
	<div id="menu">
		<div id="menu-content-wrapper">
			<div class="left">
				<p>
				<labelmenu>Diviner</labelmenu>
				</p>
			</div>
			<div class="right">
				<p>
				<!-- Check Identity -->
				Wellcome  
				<?php	
				$auth = Zend_Auth::getInstance();
				if($auth->hasIdentity()) { ?>
					<?php echo $auth->getIdentity()->lastname . ' , ' . $auth->getIdentity()->firstname ?> - 
					<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), 'default', true) ?>">Log out</a>
				<?php					
				} else {				
				?> 
					<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), 'default', true) ?>">Login</a>   
				<?php
				 } ?>							
				</p>
			</div>
		</div>
	</div>
	
	<!-- Rest of the page -->
	<div id="content-wrapper">
	
		<!-- Menu of this action -->

	   <div id="heading">
			<div class="left">				
			</div>
			<div class="right">
				
			</div>
		<p style="clear:both"></p>
		</div>
		
		<!-- Left Toolbar to browse through functionality -->
		<div class="left">
			<div id="properties">
			<ul class="aspects">
					<li class="li-diviner">
						<a
						<?php if ($this->escape($this->action) == 'Diviner') echo 'class="active"'; ?> 
						href="<?php echo $this->url(array('controller' => 'Catalogue', 'action' => 'choosewine'), 'default', true); ?>">Find Wine</a></li>
			</ul>
			</div>
			
			<?php if($auth->hasIdentity() && ( $auth->getIdentity()->profile == '1' ) ) {?>
			<div id="properties">
			<ul class="aspects">
			
					<li class="li-setts">
						<a 
						<?php if ($this->escape($this->action) == 'Catalogue') echo 'class="active"'; ?>
						href="<?php echo $this->url(array('controller' => 'catalogue', 'action' => 'index'), 'default', true); ?>">Wine Catalogue</a></li>						
					<li class="li-setts">
						<a 
						<?php if ($this->escape($this->action) == 'User') echo 'class="active"'; ?>
						href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), 'default', true); ?>">Users</a></li>						
			</ul>
			</div>
			<?php }?>
		</div>
		
		<!-- Content of the current action -->
		<div class="right">
			<div id="content">
				<h1><?php echo $this->titleView ?></h1>
				<br/>
				<?php echo $this->layout()->content;?>
			</div>
		
			<!-- Marketing -->
			<div id="legenda" style="padding-bottom:3px;" >
				<h3 style="font-size:14px;">Diviner</h3>
				<p style="font-size:11px; margin:0">Version 1.0 Oct 2011 | Developed by <a href="mailto:jfsantiagonunez@gmail.com">Jose Santiago</a></p>
			</div>
		</div>
	</div>

</body>

</html>
