<!DOCTYPE html >
<html>
<head>
	<meta charset="utf-8"/>
	<title> Devine.rs</title>
	<base href="<?php echo 'http://'.$_SERVER['SERVER_NAME'].':' . $_SERVER['SERVER_PORT'] . $this->baseUrl().'/';?>" />
	<link type="text/css" rel="stylesheet" media="handheld,screen" href="css/smartphone.css">
	<!--  <link type="text/css" rel="stylesheet" media="screen,projection" href="css/main.css">-->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script src="custom/deviners.js"></script> 
</head>
<body>
	<?php echo $this->layout()->content;?>
</body>

</html>
