

	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{	

		if ($this->descuentos)
		{			
			echo $this->table(' Descuentos <a href="'.$this->url(array('controller' => 'cliente', 
				'action' => 'adddescuento' , 'idCliente' => $this->idCliente )
				, 'default', true).'"><img src="img/icons/add.png"/></a>',
				array('descuento' => 'Descuento',	'descripcion' => 'Aplicable'),
				$this->descuentos ,
				array(
					array('controller' => 'cliente', 'action' => 'editdescuento', 'idCliente' => $this->idCliente)
				),
				array('img/icons/edit.png'),
				'idDescuento','ASC','idDescuento'); 
		}
	}
	?>
