

	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{	

		if ($this->precioscliente)
		{			
			echo $this->table(' Precios Cliente <a href="'.$this->url(array('controller' => 'cliente', 
				'action' => 'addprecio' , 'idCliente' => $this->idCliente )
				, 'default', true).'"><img src="img/icons/add.png"/></a>',
				array('descuento' => 'Descuento',	'descripcion' => 'Aplicable'),
				$this->precioscliente ,
				array(
					array('controller' => 'cliente', 'action' => 'editpreciocliente', 'idCliente' => $this->idCliente),
					array('controller' => 'cliente', 'action' => 'deletepreciocliente', 'idCliente' => $this->idCliente)
				),
				array('img/icons/edit.png','img/icons/delete.png'),
				'idPrecioCliente','ASC','idPrecioCliente'); 
		}
	}
	?>
