
	<?php
	if (isset($this->NoLoginMessage))
	{
		echo $this->NoLoginMessage;
	}
	else
	{
		if (isset($this->idTask))
		{
			$url = '<a href="'.$this->url(array('controller' => 'event', 
				'action' => 'add', 'idTask' => $this->idTask )
				, 'default', true).'"><img src="img/icons/add.png"/></a>';
		}
		else
		{
			$url = 'Summary';
		}
		if (isset($this->events) )
		{
		 echo $this->table('Calendar Events ' . $url,
				array(
					'title' => 'Title',
					'idCalendar' => 'Calendar',
					'link' => 'Event Link',
					'startdate' => 'From Date',
					'enddate' => 'To Date',
					'starttime' => 'From Time',
					'endtime' => 'To Time'
				),
				$this->events ,
				array(
					//array('controller' => 'event', 'action' => 'edit', 'idTask' => $this->idTask ),
					array('controller' => 'event', 'action' => 'delete', 'idTask' => $this->idTask )
				),
				array(/*'img/icons/edit.png',*/'img/icons/delete.png'),
				'idEvent','ASC','idEvent'); 
		}
		else
		{
			echo 'No events defined';
		
		}
	}?>
