ruby '2.2.3'
source 'http://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'

# Use MySQL as the database for Active Record on production
gem 'mysql2' , '0.3.21'

# Using Bootstrap 
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'

# Use SCSS for stylesheets
#gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# To use respond_to (it is excluded from Rails 4.2)
gem 'responders', '~> 2.0'

# Simple Form
gem 'simple_form' # See  https://github.com/plataformatec/simple_form . Install as rails generate simple_form:install --bootstrap

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

############################
# OKR specific gems required:
# For schedulled tasks, as jira import
gem 'whenever', '~> 0.9.7'

# For Active Jobs (for import test results or import jira)
gem 'sucker_punch', '~> 2.0'

# Use Chartkick for graphs visualization
gem 'chartkick'

# Access an IRB console on exception pages or by using <%= console %> in views
gem 'web-console', '~> 2.0' , group: :development

# To parse Excel sheets
gem 'spreadsheet'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  
  # helps when things go wrong
  gem 'better_errors'
end

